# Generated by Django 5.1.5 on 2025-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating_dislikes_reviewrating_likes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
