# Generated by Django 5.1.5 on 2025-03-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_reviewrating_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='comment',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
    ]
