# Generated by Django 5.1.5 on 2025-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminloginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloginattempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('HONEYPOT', 'Honeypot')], max_length=10),
        ),
    ]
