# Generated by Django 5.1.5 on 2025-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminloginattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloginattempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10),
        ),
    ]
