# Generated by Django 5.1.5 on 2025-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_variation_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='not_requested', max_length=20),
        ),
    ]
