# Generated by Django 5.1.5 on 2025-03-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
