# Generated by Django 5.1.5 on 2025-03-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitem_return_requested_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='return_status',
            new_name='refund_status',
        ),
    ]
